# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/trusty64"

  config.vm.synced_folder "./host_data", "/guest_data"

  config.vm.hostname = "updk"

  config.vm.network :public_network

 
  config.vm.provider "virtualbox" do |updk|
     updk.cpus = 4
     updk.memory = "2048"
  end

config.vm.provision "shell", inline: <<-SHELL
 #    apt-get update
 #    apt-get install -y apache2
 # mkdir /home/vagrant/kernel

 # wget -P ./kernel https://kernel.ubuntu.com/mainline/v3.14.73-trusty/linux-headers-3.14.73-031473_3.14.73-031473.201606241434_all.deb

 # wget -P ./kernel https://kernel.ubuntu.com/mainline/v3.14.73-trusty/linux-headers-3.14.73-031473-generic_3.14.73-031473.201606241434_amd64.deb

 # wget -P ./kernel https://kernel.ubuntu.com/mainline/v3.14.73-trusty/linux-image-3.14.73-031473-generic_3.14.73-031473.201606241434_amd64.deb

 # cd /home/vagrant/kernel
 
 # dpkg -i linux-headers* linux-image*

 # update-grub

 # reboot

 apt-key update

 apt-get update

SHELL
end
