# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/trusty64"

#  config.vm.synced_folder "./host_data", "/guest_data"

  config.vm.hostname = "updk"

  config.vm.network :public_network

 
  config.vm.provider "virtualbox" do |updk|
     updk.cpus = 4
     updk.memory = "2048"
     
     raid_disk1 = "/tmp/raid_disk1.vmdk"
     raid_disk2 = "/tmp/raid_disk2.vmdk"
     updk.customize ['createhd', '--filename', raid_disk1, '--size',2 * 1024]
     updk.customize ['createhd', '--filename', raid_disk2, '--size',2 * 1024]
     updk.customize ['storageattach', :id,  '--storagectl', 'SATAController', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', raid_disk1]
     updk.customize ['storageattach', :id,  '--storagectl', 'SATAController', '--port', 2, '--device', 0, '--type', 'hdd', '--medium', raid_disk2]     
  end

config.vm.provision "shell", inline: <<-SHELL
  
   apt install mdadm -y

   mdadm --create /dev/md01 -l 10 -n 2 /dev/sdb /dev/sdc

   mdadm  --manage /dev/md1 --fail /dev/sdb

   mdadm  --manage /dev/md1 --remove /dev/sdb

   mdadm --zero-superblock /dev/sdb

   mdadm  --manage /dev/md1 --add /dev/sdb
   
   sgdisk --clear /dev/md1
   
   sgdisk -o /dev/md1

   sgdisk -n 2::+200M /dev/md1

   sgdisk -n 3::+200M /dev/md1

   sgdisk -n 4::+200M /dev/md1

   sgdisk -n 5::+200M /dev/md1

   sgdisk -n 6::0 /dev/md1

   mkfs.ext4 /dev/md1p2

   mount /dev/md1p2 /mnt

   touch /mnt/testfile

   echo "/dev/md1p2 /mnt ext4 defaults 0 0" >> /etc/fstab

   reboot

SHELL
end
